repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4 # Utilise une version stable de Ruff
    hooks:
      - id: ruff
        name: ruff (lint & import sort)
        args: [--fix, --config=backend/pyproject.toml]
      - id: ruff-format
        name: ruff (formatter)
        args: [--config=backend/pyproject.toml]

  # --- ESLint Hook for Frontend ---
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.7.0 # Updated version
    hooks:
      - id: eslint
        name: eslint (frontend)
        files: \.(js|jsx|ts|tsx)$
        args: ["--config", "frontend/eslint.config.mjs", "--fix"]

  # --- Prettier Hook for Frontend ---
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0 # Updated version
    hooks:
      - id: prettier
        name: prettier (frontend)
        files: \.(js|jsx|ts|tsx|css|scss|md|json|yaml|yml)$
        args: ["--config", "frontend/.prettierrc"]
