repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4 # Utilise une version stable de Ruff
    hooks:
      - id: ruff
        name: ruff (lint & import sort)
        args: [--fix, --config=backend/pyproject.toml]
      - id: ruff-format
        name: ruff (formatter)
        args: [--config=backend/pyproject.toml]
