version: "3.8"
services:
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_worker:
    build: ./backend
    command: celery -A app.libs.celery_app.celery_app worker --loglevel=INFO
    depends_on:
      - backend
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
