[tool.ruff]
line-length = 88
# Cible la version de Python utilisée dans ton projet
# (modifie si besoin)
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.black]
line-length = 88
target-version = ["py311"] 