[tool.ruff]
line-length = 88
# Cible la version de Python utilisée dans ton projet
# (modifie si besoin)
target-version = "py311"
# E: pycodestyle (style), F: pyflakes (erreurs), I: isort (tri imports)
select = ["E", "F", "I"]
ignore = []

[tool.black]
line-length = 88
target-version = ["py311"] 